language: python
env:
  global:
    # Pypi key is too long for travis, split it in 2: https://travis-ci.community/t/travis-encrypt-data-too-large-for-pypi-tokens-with-older-repos/5792/5
    # env variables are set with SECRET1= and SECRET2= prefixes
    - secure: xCFtxc1J0FWbSCk41o8n1GpVbrBN/FdTYFgNTDgshsOlOZK7N1MdeJkmrkNeWxCcmIB9k1PqtTrH5rsr54vIoe065NAsw3xjQtioACeGuYJ/jh04XRuTInxWH6ONIixoAJ3MFX6LZELdmg1UBQI6r5dggtRS2+hswtYLlhTc9X8=
    - secure: yrpcT2OPa82rVLVSzcg4PfqsctxwWVAaOuOvU81YZSaZ3osdIOO/p+/9bNxeXvncKwOUqjtu4f6UmULNrIex/7pe4VQTI2ThjO1n3Jvt02QREFkL4doGcddGhkRqZ/8e8I+1u8ydfltQ/mcLuN4+GR8AzL4nahhfcmHEbUlZsRE=
jobs:
  include:
  - python: 3.6
    language: python
    os: linux
  - python: 3.7
    language: python
    os: linux
  - python: 3.8
    language: python
    os: linux
install:
- pip install .
script:
- ". ./ci/run_tests.sh"
deploy:
  distributions: "sdist"
  skip_existing: true
  cleanup: false
  provider: pypi
  username: __token__
  password: $SECRET1$SECRET2
  on:
    tags: true
