language: python
env:
  global:
    # Pypi key is too long for travis, split it in 2: https://travis-ci.community/t/travis-encrypt-data-too-large-for-pypi-tokens-with-older-repos/5792/5
    # env variables are set with SECRET1= and SECRET2= prefixes
    - secure: "WfqVqenEViBDdo6Mc7FQ9RvYgqp/8jZQ0FyPPDXM2FgX04WLxHzUkqKnrxHTEYtcNWlvdFHVIFsfxsvi5Vrw56DQuTw6fjjaPvKyVfSHtD+NU8E2m1L+2xMkpC2ZJMZ+ynwFF3Qw3j8NT6PS7qIUGM+swc0P7tSVid1xuUzIhUY="
    - secure: "OHOvS85p+h8ZoBoqdvS/ZBAO+YyA2hkd1ScoOpSBj9azDEXlBZeYbuib+PLxnBLmBGIsA6HBLpgZ/P3f4g56XkqndXC6U/H7Vown9NPoCWUrFqd0+Hwx3kEDVdOGIqRWwD0iu8q2ZcX1LsPXT151T+pg0B942hu2RYatBhqU58k="
jobs:
  include:
  - python: 3.6
    language: python
    os: linux
  - python: 3.7
    language: python
    os: linux
  - python: 3.8
    language: python
    os: linux
install:
- pip install .
script:
- ". ./ci/run_tests.sh"
deploy:
  distributions: "sdist"
  skip_existing: true
  cleanup: false
  provider: pypi
  username: __token__
  password: $SECRET1$SECRET2
  on:
    tags: true
